name: webapp
excludes:
  - node_modules
config:
  webroot: .
services:
  dev:
    type: node:16
    ssl: false
    port: 3000
    command: yarn dev
    globals: []
    build_as_root:
      - yarn install
  prod:
    type: node
    command: yarn start
    globals: []
    ssl: false
    port: 3000
    build_as_root:
      - yarn install
      - yarn build
# proxy:
#   webapp:
#     - webapp.lndo.site